FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml ./
COPY src ./src
COPY data/06_models ./data/06_models
RUN pip install --no-cache-dir uvicorn fastapi pydantic pydantic-settings joblib sqlalchemy psycopg2-binary pandas scikit-learn autogluon.tabular
EXPOSE 8000
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
